"""add shape to pokemon_species

Revision ID: 692554c0f8ea
Revises: d2fb19590544
Create Date: 2026-08-05 17:11:08.510650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692554c0f8ea'
down_revision: Union[str, Sequence[str], None] = 'd2fb19590544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shape', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.drop_column('shape')

    # ### end Alembic commands ###
