"""initial schema

Revision ID: 880f1d8b7240
Revises: 
Create Date: 2026-08-05 15:42:32.894477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880f1d8b7240'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ability_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_species',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('is_legendary', sa.Boolean(), nullable=False),
    sa.Column('is_mythical', sa.Boolean(), nullable=False),
    sa.Column('evolves_from_species_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evolves_from_species_id'], ['pokemon_species.species_id'], ),
    sa.PrimaryKeyConstraint('species_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('moves',
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('damage_class', sa.String(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('pp', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effect_chance', sa.Integer(), nullable=True),
    sa.Column('effect_description', sa.String(), nullable=True),
    sa.CheckConstraint("damage_class IN ('physical', 'special', 'status')", name='ck_moves_damage_class'),
    sa.ForeignKeyConstraint(['type_id'], ['types.type_id'], ),
    sa.PrimaryKeyConstraint('move_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.create_index('idx_moves_type', ['type_id'], unique=False)

    op.create_table('pokedex_entries',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('entry', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.species_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['game_versions.version_id'], ),
    sa.PrimaryKeyConstraint('species_id', 'version_id', 'language')
    )
    op.create_table('pokemon_forms',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('form_name', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('sprite_url', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('special_attack', sa.Integer(), nullable=False),
    sa.Column('special_defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('base_stat_total', sa.Integer(), sa.Computed('hp + attack + defense + special_attack + special_defense + speed', persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id')
    )
    with op.batch_alter_table('pokemon_forms', schema=None) as batch_op:
        batch_op.create_index('idx_pokemon_forms_species', ['species_id'], unique=False)
        batch_op.create_index('ux_pokemon_forms_base', ['species_id'], unique=True, sqlite_where=sa.text('form_name IS NULL'))

    op.create_table('type_efficacy',
    sa.Column('damage_type_id', sa.Integer(), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.Column('damage_factor', sa.Float(), nullable=False),
    sa.CheckConstraint('damage_factor IN (0, 0.5, 1, 2)', name='ck_type_efficacy_damage_factor'),
    sa.ForeignKeyConstraint(['damage_type_id'], ['types.type_id'], ),
    sa.ForeignKeyConstraint(['target_type_id'], ['types.type_id'], ),
    sa.PrimaryKeyConstraint('damage_type_id', 'target_type_id')
    )
    op.create_table('pokemon_abilities',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.ability_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id', 'ability_id')
    )
    op.create_table('pokemon_enrichment',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('physical_traits', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_table('pokemon_moves',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('learn_method', sa.String(), nullable=False),
    sa.Column('level_learned_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("learn_method IN ('level-up', 'machine', 'egg', 'tutor')", name='ck_pokemon_moves_learn_method'),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['move_id'], ['moves.move_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id', 'move_id', 'learn_method', 'level_learned_at')
    )
    with op.batch_alter_table('pokemon_moves', schema=None) as batch_op:
        batch_op.create_index('idx_pokemon_moves_move', ['move_id'], unique=False)

    op.create_table('pokemon_types',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.CheckConstraint('slot IN (1, 2)', name='ck_pokemon_types_slot'),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['types.type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id', 'type_id')
    )
    with op.batch_alter_table('pokemon_types', schema=None) as batch_op:
        batch_op.create_index('idx_pokemon_types_type', ['type_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_types', schema=None) as batch_op:
        batch_op.drop_index('idx_pokemon_types_type')

    op.drop_table('pokemon_types')
    with op.batch_alter_table('pokemon_moves', schema=None) as batch_op:
        batch_op.drop_index('idx_pokemon_moves_move')

    op.drop_table('pokemon_moves')
    op.drop_table('pokemon_enrichment')
    op.drop_table('pokemon_abilities')
    op.drop_table('type_efficacy')
    with op.batch_alter_table('pokemon_forms', schema=None) as batch_op:
        batch_op.drop_index('ux_pokemon_forms_base', sqlite_where=sa.text('form_name IS NULL'))
        batch_op.drop_index('idx_pokemon_forms_species')

    op.drop_table('pokemon_forms')
    op.drop_table('pokedex_entries')
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_index('idx_moves_type')

    op.drop_table('moves')
    op.drop_table('types')
    op.drop_table('pokemon_species')
    op.drop_table('game_versions')
    op.drop_table('abilities')
    # ### end Alembic commands ###
