"""drop pokemon_species.color, normalized into pokemon_colors

Revision ID: 9b96ec3b1b09
Revises: 7c347e08818e
Create Date: 2026-08-12 19:21:09.606806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b96ec3b1b09'
down_revision: Union[str, Sequence[str], None] = '7c347e08818e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
