"""add held items, game indices, past data, cries

Revision ID: abf18a89bb8c
Revises: ae19657a9a2f
Create Date: 2026-08-12 17:30:26.406875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf18a89bb8c'
down_revision: Union[str, Sequence[str], None] = 'ae19657a9a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_cries',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('latest', sa.String(), nullable=True),
    sa.Column('legacy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_table('pokemon_game_indices',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('game_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['game_versions.version_id'], ),
    sa.PrimaryKeyConstraint('form_id', 'version_id')
    )
    op.create_table('pokemon_held_items',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['game_versions.version_id'], ),
    sa.PrimaryKeyConstraint('form_id', 'item_id', 'version_id')
    )
    op.create_table('pokemon_past_abilities',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.ability_id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id', 'generation', 'slot')
    )
    op.create_table('pokemon_past_stats',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('stat_name', sa.String(), nullable=False),
    sa.Column('base_stat', sa.Integer(), nullable=False),
    sa.Column('effort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id', 'generation', 'stat_name')
    )
    op.create_table('pokemon_past_types',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('slot IN (1, 2)', name='ck_pokemon_past_types_slot'),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['types.type_id'], ),
    sa.PrimaryKeyConstraint('form_id', 'generation', 'slot')
    )
    with op.batch_alter_table('pokemon_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_forms', schema=None) as batch_op:
        batch_op.drop_column('order')
        batch_op.drop_column('base_experience')

    op.drop_table('pokemon_past_types')
    op.drop_table('pokemon_past_stats')
    op.drop_table('pokemon_past_abilities')
    op.drop_table('pokemon_held_items')
    op.drop_table('pokemon_game_indices')
    op.drop_table('pokemon_cries')
    op.drop_table('items')
    # ### end Alembic commands ###
