"""add color to pokemon_species

Revision ID: ae19657a9a2f
Revises: 692554c0f8ea
Create Date: 2026-08-05 18:38:43.998788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae19657a9a2f'
down_revision: Union[str, Sequence[str], None] = '692554c0f8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_species', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
