"""add locations and pokemon_location_encounters tables

Revision ID: ed4cb632557f
Revises: 9b96ec3b1b09
Create Date: 2026-08-13 11:04:19.431962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4cb632557f'
down_revision: Union[str, Sequence[str], None] = '9b96ec3b1b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_location_encounters',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('chance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.form_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['game_versions.version_id'], ),
    sa.PrimaryKeyConstraint('form_id', 'location_id', 'version_id', 'method', 'min_level', 'max_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_location_encounters')
    op.drop_table('locations')
    # ### end Alembic commands ###
